"""ability to reject the appeal

Revision ID: 913a0eacd19f
Revises: 5cdd91ae6e96
Create Date: 2026-09-01 10:52:40.195408

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '913a0eacd19f'
down_revision: Union[str, Sequence[str], None] = '5cdd91ae6e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('consultations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('medical_history', 'date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    # manually added: expand notificationtype enum to include the rejection type
    op.alter_column(
        'notifications',
        'type',
        existing_type=mysql.ENUM(
            'appointment_booked', 'appointment_confirmed', 'appointment_cancelled',
            'appointment_completed', 'doctor_registered', 'doctor_verified',
            'patient_verification_requested', 'patient_verified',
            'consultation_created', 'prescription_created', 'system',
        ),
        type_=mysql.ENUM(
            'appointment_booked', 'appointment_confirmed', 'appointment_cancelled',
            'appointment_completed', 'doctor_registered', 'doctor_verified',
            'patient_verification_requested', 'patient_verified',
            'patient_verification_rejected',
            'consultation_created', 'prescription_created', 'system',
        ),
        existing_nullable=False,
    )

    op.add_column('patients', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('prescriptions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('prescriptions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.drop_column('patients', 'rejection_reason')

    # manually added: revert enum
    op.alter_column(
        'notifications',
        'type',
        existing_type=mysql.ENUM(
            'appointment_booked', 'appointment_confirmed', 'appointment_cancelled',
            'appointment_completed', 'doctor_registered', 'doctor_verified',
            'patient_verification_requested', 'patient_verified',
            'patient_verification_rejected',
            'consultation_created', 'prescription_created', 'system',
        ),
        type_=mysql.ENUM(
            'appointment_booked', 'appointment_confirmed', 'appointment_cancelled',
            'appointment_completed', 'doctor_registered', 'doctor_verified',
            'patient_verification_requested', 'patient_verified',
            'consultation_created', 'prescription_created', 'system',
        ),
        existing_nullable=False,
    )

    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('medical_history', 'date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('consultations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('appointments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    # ### end Alembic commands ###
