"""add security question to doctors and patients

Revision ID: f89d4a0a4829
Revises: 9cad9f8335a8
Create Date: 2026-07-30 17:39:14.192994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f89d4a0a4829'
down_revision: Union[str, Sequence[str], None] = '9cad9f8335a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('consultations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('doctors', sa.Column('security_answer_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('medical_history', 'date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('patients', sa.Column('security_answer_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('prescriptions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('prescriptions', 'follow_up_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('prescriptions', 'follow_up_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('prescriptions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.drop_column('patients', 'security_answer_hash')
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('medical_history', 'date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.drop_column('doctors', 'security_answer_hash')
    op.alter_column('consultations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('appointments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    # ### end Alembic commands ###
